### ISSUE TITLE
Master build should automatically merge devel into master branch

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esgf-build#25]
Currently the build process doesn't automatically merge the devel branch into the master branch when building a master distribution.

The code at the relevant devel tag should be merged into master automatically when building master.

**Comment by sashakames** [comment]
for 2.x the tag is in esg-init - but this would change for 3.0
A corollary for this is that for devel builds, the tag used should be derived from esg-init or tag manifest file rather than a straight-up git describe.
